# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainClassWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QListWidget, QListWidgetItem,
    QMainWindow, QMenu, QMenuBar, QProgressBar,
    QPushButton, QScrollArea, QSizePolicy, QStatusBar,
    QTabWidget, QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1306, 612)
        self.actionNew_Template = QAction(MainWindow)
        self.actionNew_Template.setObjectName(u"actionNew_Template")
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        self.action_4 = QAction(MainWindow)
        self.action_4.setObjectName(u"action_4")
        self.action_5 = QAction(MainWindow)
        self.action_5.setObjectName(u"action_5")
        self.action_7 = QAction(MainWindow)
        self.action_7.setObjectName(u"action_7")
        self.action_8 = QAction(MainWindow)
        self.action_8.setObjectName(u"action_8")
        self.action_9 = QAction(MainWindow)
        self.action_9.setObjectName(u"action_9")
        self.action_11 = QAction(MainWindow)
        self.action_11.setObjectName(u"action_11")
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.action_3 = QAction(MainWindow)
        self.action_3.setObjectName(u"action_3")
        self.action_6 = QAction(MainWindow)
        self.action_6.setObjectName(u"action_6")
        self.action_12 = QAction(MainWindow)
        self.action_12.setObjectName(u"action_12")
        self.action_13 = QAction(MainWindow)
        self.action_13.setObjectName(u"action_13")
        self.action_10 = QAction(MainWindow)
        self.action_10.setObjectName(u"action_10")
        self.action_14 = QAction(MainWindow)
        self.action_14.setObjectName(u"action_14")
        self.action_16 = QAction(MainWindow)
        self.action_16.setObjectName(u"action_16")
        self.action_17 = QAction(MainWindow)
        self.action_17.setObjectName(u"action_17")
        self.action_18 = QAction(MainWindow)
        self.action_18.setObjectName(u"action_18")
        self.action_15 = QAction(MainWindow)
        self.action_15.setObjectName(u"action_15")
        self.action_19 = QAction(MainWindow)
        self.action_19.setObjectName(u"action_19")
        self.action_20 = QAction(MainWindow)
        self.action_20.setObjectName(u"action_20")
        self.action_21 = QAction(MainWindow)
        self.action_21.setObjectName(u"action_21")
        self.action_22 = QAction(MainWindow)
        self.action_22.setObjectName(u"action_22")
        self.action_23 = QAction(MainWindow)
        self.action_23.setObjectName(u"action_23")
        self.action_24 = QAction(MainWindow)
        self.action_24.setObjectName(u"action_24")
        self.action_25 = QAction(MainWindow)
        self.action_25.setObjectName(u"action_25")
        self.action_26 = QAction(MainWindow)
        self.action_26.setObjectName(u"action_26")
        self.action_28 = QAction(MainWindow)
        self.action_28.setObjectName(u"action_28")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 0, 941, 341))
        self.tabWidget_2.setStyleSheet(u"QTabWidget::pane {\n"
"    background: transparent;\n"
"    border:1;\n"
"}\n"
"\n"
"")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.scrollArea = QScrollArea(self.tab_3)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 0, 901, 321))
        self.scrollArea.setStyleSheet(u"background: transparent;border:1;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 901, 321))
        self.scrollAreaWidgetContents_2.setMinimumSize(QSize(0, 0))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(0, 360, 951, 201))
        self.textBrowser.setStyleSheet(u"background-color: rgba(255, 255, 255, 127);\n"
"border-color: rgb(12, 12, 12);")
        self.listWidget = QListWidget(self.centralwidget)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(980, 180, 321, 221))
        self.listWidget.setStyleSheet(u"background-color: rgba(255, 255, 255, 127);")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(980, 160, 171, 21))
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(1070, 150, 231, 23))
        self.progressBar.setValue(24)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(990, 410, 291, 151))
        self.tabWidget.setStyleSheet(u"background-color: rgba(255, 255, 255, 127);")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_2 = QLabel(self.tab_5)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 191, 16))
        self.label_3 = QLabel(self.tab_5)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 40, 191, 16))
        self.label_4 = QLabel(self.tab_5)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 60, 181, 16))
        self.label_5 = QLabel(self.tab_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 80, 191, 16))
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 191, 21))
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 30, 191, 21))
        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 50, 191, 21))
        self.label_10 = QLabel(self.tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 70, 191, 21))
        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 90, 261, 21))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton = QPushButton(self.tab_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(100, 50, 75, 24))
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(970, -24, 75, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.raise_()
        self.tabWidget_2.raise_()
        self.textBrowser.raise_()
        self.listWidget.raise_()
        self.progressBar.raise_()
        self.tabWidget.raise_()
        self.pushButton_2.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1306, 22))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        self.menu_4 = QMenu(self.menubar)
        self.menu_4.setObjectName(u"menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menu.addAction(self.actionNew_Template)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menu.addAction(self.action_19)
        self.menu.addAction(self.action_22)
        self.menu.addAction(self.action_18)
        self.menu.addAction(self.action_7)
        self.menu.addSeparator()
        self.menu.addAction(self.action_12)
        self.menu.addAction(self.action_13)
        self.menu.addSeparator()
        self.menu.addAction(self.action_20)
        self.menu.addAction(self.action_21)
        self.menu_2.addAction(self.action_8)
        self.menu_2.addAction(self.action_9)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action)
        self.menu_3.addAction(self.action_15)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_3)
        self.menu_3.addAction(self.action_23)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_24)
        self.menu_3.addAction(self.action_25)
        self.menu_3.addAction(self.action_26)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_28)
        self.menu_4.addAction(self.action_10)
        self.menu_4.addAction(self.action_14)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_16)
        self.menu_4.addAction(self.action_17)

        self.retranslateUi(MainWindow)

        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u4e3b\u754c\u9762", None))
        self.actionNew_Template.setText(QCoreApplication.translate("MainWindow", u"\u521b\u5efa\u65b0\u6a21\u677f", None))
#if QT_CONFIG(shortcut)
        self.actionNew_Template.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u677f\u7ba1\u7406", None))
#if QT_CONFIG(shortcut)
        self.action_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.action_4.setText(QCoreApplication.translate("MainWindow", u"\u53d1\u9001\u70b9\u8bc4\uff08\u5355\u9009\uff09", None))
#if QT_CONFIG(shortcut)
        self.action_4.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action_5.setText(QCoreApplication.translate("MainWindow", u"\u53d1\u9001\u70b9\u8bc4", None))
#if QT_CONFIG(shortcut)
        self.action_5.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.action_7.setText(QCoreApplication.translate("MainWindow", u"\u64a4\u56de\u4e0a\u6b65", None))
#if QT_CONFIG(shortcut)
        self.action_7.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.action_8.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u7ec4\u89c6\u56fe", None))
#if QT_CONFIG(shortcut)
        self.action_8.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.action_9.setText(QCoreApplication.translate("MainWindow", u"\u4e2a\u4eba\u89c6\u56fe", None))
#if QT_CONFIG(shortcut)
        self.action_9.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.action_11.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u5fd7\u83dc\u5355", None))
#if QT_CONFIG(shortcut)
        self.action_11.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u73ed\u7ea7\u6392\u540d", None))
#if QT_CONFIG(shortcut)
        self.action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.action_3.setText(QCoreApplication.translate("MainWindow", u"\u5de5\u5177\u8bbe\u7f6e", None))
#if QT_CONFIG(shortcut)
        self.action_3.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+,", None))
#endif // QT_CONFIG(shortcut)
        self.action_6.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
#if QT_CONFIG(shortcut)
        self.action_6.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_12.setText(QCoreApplication.translate("MainWindow", u"\u5468\u7ed3\u7b97", None))
#if QT_CONFIG(shortcut)
        self.action_12.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.action_13.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u5386\u53f2\u8bb0\u5f55", None))
#if QT_CONFIG(shortcut)
        self.action_13.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.action_10.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u5b58\u6863", None))
#if QT_CONFIG(shortcut)
        self.action_10.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_14.setText(QCoreApplication.translate("MainWindow", u"\u5c06\u5b58\u6863\u53e6\u5b58\u4e3a", None))
#if QT_CONFIG(shortcut)
        self.action_14.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+J", None))
#endif // QT_CONFIG(shortcut)
        self.action_16.setText(QCoreApplication.translate("MainWindow", u"\u52a0\u8f7d\u8fd8\u539f\u70b9", None))
#if QT_CONFIG(shortcut)
        self.action_16.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.action_17.setText(QCoreApplication.translate("MainWindow", u"\u521b\u5efa\u8fd8\u539f\u70b9", None))
#if QT_CONFIG(shortcut)
        self.action_17.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.action_18.setText(QCoreApplication.translate("MainWindow", u"\u536b\u751f\u7ed3\u7b97", None))
#if QT_CONFIG(shortcut)
        self.action_18.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.action_15.setText(QCoreApplication.translate("MainWindow", u"\u64ad\u653e\u97f3\u4e50", None))
#if QT_CONFIG(shortcut)
        self.action_15.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.action_19.setText(QCoreApplication.translate("MainWindow", u"\u8003\u52e4\u8bb0\u5f55", None))
#if QT_CONFIG(shortcut)
        self.action_19.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.action_20.setText(QCoreApplication.translate("MainWindow", u"\u5168\u73ed\u95ed\u5634", None))
#if QT_CONFIG(shortcut)
        self.action_20.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action_21.setText(QCoreApplication.translate("MainWindow", u"\u968f\u673a\u62bd\u4eba", None))
#if QT_CONFIG(shortcut)
        self.action_21.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_22.setText(QCoreApplication.translate("MainWindow", u"\u4f5c\u4e1a\u7ed3\u7b97", None))
#if QT_CONFIG(shortcut)
        self.action_22.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.action_23.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e\u5de5\u5177", None))
        self.action_24.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u65b0\u65e5\u5fd7", None))
        self.action_25.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u66f4\u65b0", None))
        self.action_26.setText(QCoreApplication.translate("MainWindow", u"\u5237\u65b0\u7a97\u53e3", None))
        self.action_28.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u8bd5\u9879\u76ee", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u672c\u73ed\u5b66\u751f", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u672c\u73ed\u5c0f\u7ec4", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u7cfb\u7edf\u4e8b\u4ef6", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"\u73ed\u7ea7\u4fe1\u606f", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3\u66f4\u65b0\u7387: 0/\u79d2", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u8fd0\u884c\u65f6\u95f4: ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u5e76\u884c\u7ebf\u7a0b\u6570: 0", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u5185\u5b58\u5360\u7528\uff1a114MB", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u5185\u90e8\u66f4\u65b0\u7387\uff1a114", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u7cfb\u7edf\u4fe1\u606f", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u5343\u4e07\u522b\u70b9", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u62bd\u8c61\u529f\u80fd", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u8df3\u8fc7\u6240\u6709", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u64cd\u4f5c", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u5176\u4ed6", None))
        self.menu_4.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
    # retranslateUi

