name: 发布版本

on:
  workflow_call:
    inputs:
      run_id:
        description: 'Get RunID'
        required: true
        type: string
  push:
    tags:
      - 'release/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-x64
          path: zip
          run_id: ${{ inputs.run_id }}

      - name: Get Version
        id: get_version
        run: |
          echo "version=${GITHUB_REF#refs/tags/release/}" >> $GITHUB_OUTPUT

      - name: Init Changelog
        id: init_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: |
            template: |+
              ## 更新日志 🎉
              {{ changelog }}
              **完整更新日志**: {{releaseUrl}}
            commitMode: "angular"
            failOnError: false
            exclude:
              labels:
                - 'skip-changelog'
                - 'duplicate'
                - 'invalid'
            categories:
              - title: '🚀 新功能'
                labels:
                  - 'feat'
                  - 'feature'
                  - 'enhancement'
              - title: '🐛 Bug修复'
                labels:
                  - 'bug'
                  - 'fix'
              - title: '⚡ 性能优化'
                labels:
                  - 'perf'
                  - 'performance'
              - title: '💄 界面优化'
                labels:
                  - 'style'
                  - 'ui'
              - title: '📚 文档更新'
                labels:
                  - 'docs'
                  - 'documentation'
              - title: '♻️ 代码重构'
                labels:
                  - 'refactor'
              - title: '🔧 其他更新'
                labels:
                  - 'chore'
                  - 'build'
                  - 'ci'
                  - 'test'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release/${{ steps.get_version.outputs.version }}
          name: 版本 ${{ steps.get_version.outputs.version }}
          body: ${{ steps.init_changelog.outputs.changelog }}
          prerelease: false
          draft: false
          files: |
            zip/*.zip